name: Hello Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls -la

      - name: Find Files
        run: find .

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check CSV
        run: python3 scripts/check_csv.py
